apecloud/kubeblocks.io

docs/OpenCli/manual.md

process test

---

.gitignore

ignore vscode

---

static/installer/install_cli.ps1
static/installer/install_cli.sh

- adjust the linux and mac install_cli.sh
- add a powershell install script for windows OS

add powershell script

---

static/installer/install_cli.ps1
static/installer/install_cli.sh

adjust the install_cli.sh

---

config/footer.js

feat: slack url

---

blog/does-running-mysql-on-kubernetes-lead-to-significant-performance-degradation.md
docusaurus.config.js

feat: blog slug

---

config/footer.js
config/navbar.js

feat:hidden blog

---

blog/does-running-mysql-on-kubernetes-lead-to-significant-performance-degradation.md

feat: blog

---

config/footer.js

feat: footer

---

blog/a-testing-report-for-postgreSQL-K8s.md

feat: blog img

---

docusaurus.config.js
src/style/custom.less

feat: add announcement bar

---

src/style/custom.less

feat: media

---

docusaurus.config.js
src/style/custom.less

feat: announcement bar

---

.github/workflows/deploy.yml

fix: docs add 0.7

---

docusaurus.config.js

feat: remove announcementBar

---

src/pages/index.module.less
src/pages/index.tsx

feat: add book btn

---

.github/workflows/deploy.yml
scripts/docs/utils.js

- fix #155 
support kbcli repo docs

fix: support kbcli docx

---

.github/workflows/deploy.yml
scripts/docs/utils.js

Reverts apecloud/kubeblocks.io#158

Revert "fix: support kbcli docx"

---

docusaurus.config.js

feat: tagline

---

config/footer.js

docs: update slack link

---

config/navbar.js
src/style/custom.less

feat: Language switch

---

config/navbar.js

feat: target self

---

package.json
src/components/docItemComponent.tsx
src/components/kubechat/index.js
src/pages/index.module.less
src/style/custom.less
yarn.lock

feat: add kubechat

---

src/components/docItemComponent.tsx

feat: chat

---

docusaurus.config.js

fix: remove version docs

---

.github/workflows/docsearch.yml

fix: remove schedule

---

.github/workflows/docsearch.yml
docsearch.json
docusaurus.config.js

fix: algolia search

---

.github/ISSUE_TEMPLATE/bug_report.md
.github/ISSUE_TEMPLATE/document-request.md
.github/ISSUE_TEMPLATE/feature_request.md
.github/ISSUE_TEMPLATE/improvement-request.md

fix: issue template

---

src/pages/index.module.less
src/pages/index.tsx

feat: add btn

---

src/pages/index.module.less
src/pages/index.tsx
src/pages/typeWriter.less

feat: banner text

---

src/pages/index.module.less

feat: home

---

static/js/kubechat.js

fix: kubechat

---

src/pages/chatInput.less
src/pages/chatInput.tsx
src/pages/index.tsx
static/js/kubechat.js

feat: homepage add chat

---

src/pages/chatInput.less
src/pages/index.tsx

banner text

---

static/js/kubechat.js

feat: update kubechat

---

src/style/custom.less

fix: table_text_word_break

---

static/yamls/dify/postgresql.yaml
static/yamls/dify/qdrant.yaml
static/yamls/dify/redis.yaml

chore: add dify related yamls

---

static/yamls/dify/postgresql.yaml
static/yamls/dify/qdrant.yaml

chore: update qdrant and pg cluster resources

---

blog/Moodle in Kubeblocks（windows）.md

I have written a how-to blog post about how to deploy Moodle using the database on Kubeblocks on Windows.

Add moodle-in-kubeblocks.md document

---

config/footer.js
config/navbar.js
src/pages/index.tsx

fix: api docs homepage

---

src/pages/index.tsx

feat: Copy update

---

src/pages/index.tsx

fix: page url error

---

static/report/kubeblocks/v0.9.1/TEST_REPORT_ALL.html
static/report/kubeblocks/v0.9.1/TEST_REPORT_CHAOS.html
static/report/kubeblocks/v0.9.1/TEST_REPORT_SMOKE.html
static/report/kubeblocks/v0.9.1/TEST_REPORT_UPGRADE.html

chore: add kubeblocks v0.9.1 report

---

docusaurus.config.ts

fix: set trailingSlash

---

config/navbar.js
src/pages/index.tsx
src/theme/DocSidebar/Desktop.tsx

fix: sidebar version change

---

src/pages/index.tsx

fix: try kubeblocks
